services:
  web:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./service:/service

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8080"

    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass

  rabbitmq:
    restart: always
    image: rabbitmq:latest
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - "5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service:/service
    links:
      - rabbitmq
    depends_on:
      - rabbitmq